name: linearprogrammingapp
description: This is an open-source project, that aims to provide a linear programming solver, using the Flutter SDK. Leveraging the power of Flutter's cross-platform capabilities, the project offers a user-friendly interface and efficient algorithms to solve linear programming problems.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  appwrite: 8.3.0
  flutter_riverpod: ^2.4.4
  freezed_annotation: ^2.4.1
  go_router: ^11.1.4
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.2.1
  window_location_href: ^1.0.1+2
  hive_flutter: ^1.1.0
  flutter_math_fork: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/img/
  fonts:
    - family: CMClassic
      fonts:
        - asset: assets/fonts/cmunci.ttf
    - family: CMRomanSerif
      fonts:
        - asset: assets/fonts/cmunrm.ttf